# Generated by Django 3.0.7 on 2020-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200728_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Show'), (2, 'Hide')], null=True),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
