# Generated by Django 3.0.7 on 2020-07-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200728_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatagory',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Show'), (2, 'Hide')], null=True),
        ),
    ]
