# Generated by Django 3.0.7 on 2020-07-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subcatagory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat_id',
            field=models.IntegerField(choices=[(1, 'Women wear'), (2, 'Man wear'), (3, 'Children'), (4, 'Bags and Purses'), (5, 'Eyewear'), (6, 'Footwear')], null=True),
        ),
    ]
