# Generated by Django 3.0.7 on 2020-07-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200728_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatagory',
            name='cat_id',
            field=models.IntegerField(null=True),
        ),
    ]
