# Generated by Django 3.0.7 on 2020-07-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200728_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subCatagory'),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catagory'),
        ),
    ]
