# Generated by Django 3.0.7 on 2020-07-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200728_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catagory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catagory'),
        ),
        migrations.DeleteModel(
            name='subCatagory',
        ),
    ]
