# Generated by Django 3.0.7 on 2020-07-28 11:53

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200728_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcatagory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Newcatagory'),
        ),
    ]
