# Generated by Django 3.0.7 on 2020-07-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200728_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Show'), (2, 'Hide')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Show'), (2, 'Hide')], null=True)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Catagory')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='Newcatagory',
        ),
        migrations.AddField(
            model_name='products',
            name='sub_cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subCatagory'),
        ),
    ]
