# Generated by Django 3.0.7 on 2020-07-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200728_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subCatagory'),
        ),
    ]
