# Generated by Django 3.0.7 on 2020-07-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200728_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcatagory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.newCatagory'),
        ),
    ]
