# Generated by Django 3.0.7 on 2020-07-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200728_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='newProducts',
        ),
    ]
